# Build stage
FROM golang:1.21-alpine AS build

WORKDIR /src

COPY src/shared shared
COPY src/producer producer

WORKDIR /src/producer

RUN go mod tidy
RUN go mod download
RUN go build -o producer .

# Runtime stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY --from=build /src/producer/producer .

CMD ["./producer"]