version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.9
    environment:
      ZOO_CFG_SERVER_1: zookeeper:2888:3888
    cpus: '0.5'
    mem_limit: 512M
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - epedidos-net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    cpus: '1.0'
    mem_limit: 1G
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - epedidos-net

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    cpus: '1.0'
    mem_limit: 1G
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - epedidos-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  producer:
    build:
      context: .
      dockerfile: Dockerfile.Producer
    depends_on:
      - kafka
    cpus: '0.5'
    mem_limit: 512M
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - epedidos-net

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.Consumer
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    cpus: '0.5'
    mem_limit: 512M
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - epedidos-net

networks:
  epedidos-net:
    driver: bridge

volumes:
  postgres_data: