# Build stage
FROM golang:1.21-alpine AS build

WORKDIR /src

COPY src/shared shared
COPY src/consumer consumer

WORKDIR /src/consumer

RUN go mod tidy
RUN go mod download
RUN go build -o consumer .

# Runtime stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY --from=build /src/consumer/consumer .

CMD ["./consumer"]